name: balena

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
      matrix:
        fleet: [gh_klutchell/pi-hole, klutchell_apps/pi-hole]

    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - uses: balena-io/deploy-to-balena-action@f009d295ed6904859c7b99a5637855d9e3ee670e # v1.0.2
        with:
          balena_token: ${{ secrets.BALENA_API_KEY }}
          fleet: ${{ matrix.fleet }}
          create_tag: true
